### ISSUE TITLE
Norman fails while extracting CallArg

### ISSUE THREAD

**Issue by arindam-8** [srg-imperial/norman#2] opened 2024-05-06 13:48 UTC
Following is a standalone testcase:

```C
/* The kinds of value we can have.  */
enum valtype
{
  integer,
  string
};
typedef enum valtype TYPE;
/* A value is.... */
struct valinfo
{
  TYPE type;			/* Which kind. */
  union
  {				/* The value itself. */
    int i;
    char *s;
  } u;
};
typedef struct valinfo VALUE;
int i =0;
int main(){

  VALUE *v = malloc (sizeof *v);
  v->type = integer;
  v->u.i = i;
  return v;

}

```

Preprocessing the file and then running norman on it results in the following failure:

```C
test.c:22:44: error: use of undeclared identifier 'v'
  unsigned long _CallArg_main_1 = (sizeof *v);
                                           ^
1 error generated.
Error while processing /workspaces/norman-submod/build/test-pp.c.
```

This is with the latest version of `norman`. 
Let me know if I might have missed something.

**Comment by danielschemmel** [comment] 2024-05-07 00:05
A minimized example might look like:
```c
int foo(int n) { return n; }

int main(){
  int v = foo(sizeof v);
}
```
which normalizes to
```c
int foo(int n) { return n; }

int main() {
	int _CallArg_main_1 = (sizeof v);
	int v;
	v = (foo(_CallArg_main_1));
}
```

While it seems as if just computing `sizeof v` statically might be a solution, the same issue crops up with the following example:
```c
int foo(int* n) { return 0; }

int main(){
  int v = foo(&v);
}
```

A valid normalization of this example would be:
```c
int foo(int* n) { return 0; }

int main() {
	int v;  // the declaration of `v` needs to be at the very top. 
	int* _CallArg_main_1;
	_CallArg_main_1 = (&v);
	v = (foo(_CallArg_main_1));
}
```

**Comment by danielschemmel** [comment] 2024-05-07 00:23
Alright, turns out that there is actually a class of transformations that require VarDecl splitting to be valid, one of which we just triggered here.

The issue is caused specifically because the VarDecl splitting was disabled in the case of the initializer referencing the newly declared variable.

I have pushed a fix in 384f0462fb5df9f4f591d0ccc6f0abe8f90792f3, which should deal with this issue **unless `VarDecl.graceful` is true**. With default configuration, norman should crash if the VarDecl splitting cannot be performed correctly.

**Comment by danielschemmel** [comment] 2024-05-07 04:34
Note: 008d6920fcad5c6e66579a5ff804fc6e9c044790 significantly improves VarDecl splitting further. It also **removes VarDecl.graceful**, as there is no case left where it would have any effect.

It also enables **Vardecl.remove local const** by default, although it may cause detectable semantic differences, as we need to stop execution when VarDecl splitting fails (due to the issue discussed here).

**Comment by ccadar** [comment] 2024-05-07 10:49
@danielschemmel sounds great.
Are you now declaring the variable first in these examples?

**Comment by danielschemmel** [comment] 2024-05-07 11:10
@ccadar Yes, the underlying failure was that VarDecls were not split, which they now are.

**Comment by ccadar** [comment] 2024-05-07 11:12
Thanks!

**Closed as completed** 2024-05-07 17:30 UTC
